In [36]:
import numpy as np
np.random.seed(42)
# Дано: два массива размера 10000
a = np.random.rand(10000)
b = np.random.rand(10000)

# 1) Через цикл (медленно)
def with_loop(a, b):
    result = np.zeros(len(a))
    for i in range(len(a)):
        result[i] = a[i] * b[i]
    return result

# 2) Через векторизацию (быстро)
def with_vectorized(a, b):
    return a * b

# Сравнение времени выполнения
if __name__ == "__main__":
    print("Цикл:")
    %timeit with_loop(a, b)

    print("\nВекторизация:")
    %timeit with_vectorized(a, b)

Цикл:
4.05 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Векторизация:
7.14 μs ± 171 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [37]:
# Дано: матрица 100x50 и вектор 50
np.random.seed(42)
matrix = np.random.rand(100, 50)
vector = np.random.rand(50)

# Прибавил vector к каждой строке matrix с помощью broadcasting
print(matrix+vector)

[[0.76817564 1.42414997 1.58654134 ... 1.04872463 0.88115281 0.70416715]
 [1.36322015 1.24856848 1.79404633 ... 0.95619762 0.35986165 0.62720412]
 [0.42506471 1.10984607 1.16890337 ... 1.03133563 0.38592128 0.79795916]
 ...
 [1.3748931  0.85505216 1.62978193 ... 0.82663384 0.42420203 1.43013896]
 [0.39968256 0.95729588 0.97779485 ... 1.27028389 1.13953984 1.36435234]
 [0.78868886 0.52469912 1.25642366 ... 0.85649944 1.15018791 1.11662507]]


In [38]:
# Дано: массив (1000, 20) - 1000 примеров, 20 признаков
np.random.seed(42)
data = np.random.randn(1000, 20)
# normalized = (data - mean) / std
# Нормализовать каждый признак (column-wise)
normalized = (data - data.mean(axis=0)) / data.std(axis=0) #axis=0 для операции по столбцам (признакам)
print(normalized)

[[ 0.45754837 -0.15952569  0.71770032 ...  0.3050184  -0.8960248
  -1.50259403]
 [ 1.41282159 -0.25148964  0.14287038 ... -1.93744089 -1.30909859
   0.19080875]
 [ 0.69589223  0.16585868 -0.03862312 ... -0.30981615  0.32235578
   1.0102558 ]
 ...
 [-0.71433745  0.50066039  1.02720264 ... -2.58416718  1.71444204
   0.56846525]
 [-0.14728023 -0.7153941  -2.77364529 ... -1.02361909  0.69837523
   0.32878131]
 [ 0.9168576   0.5244492  -0.67022954 ...  0.36823817  1.68130309
  -1.72107858]]


In [52]:
# Дано: массив оценок студентов
np.random.seed(42)
grades = np.random.randint(0, 101, size=(100, 5))  # 100 студентов, 5 экзаменов
student_means = grades.mean(axis=1)  # среднее по каждому студенту (по строкам)
students_high_achievers = student_means > 80
indices_high_achievers = np.where(students_high_achievers)[0]  # индексы студентов
print(f"1) Студентов со средним баллом > 80: {students_high_achievers.sum()}")
print(f"   Индексы студентов: {indices_high_achievers}")
print(f"   Их средние баллы: {student_means[students_high_achievers]}")

exam_means = grades.mean(axis=0)
exam_low_average = exam_means < 60
includes_low_exam = np.where(exam_low_average)[0]
print(f"2) Экзамены со средним баллом < 60: {exam_low_average.sum()}")
print(f"   Индексы экзаменов: {includes_low_exam}")
print(f"   Средние баллы экзамена: {exam_means[exam_low_average]}")

grades_copy = grades.copy()
grades_copy[grades_copy < 40] = 40
print(f"3) Массив оценок после изменения оценок < 40 на 40 (пересдача):\n{grades_copy[:10]}")
# 1) Найти студентов со средним баллом > 80
# 2) Найти экзамены, где средний балл < 60
# 3) Заменить все оценки < 40 на 40 (пересдача)

1) Студентов со средним баллом > 80: 3
   Индексы студентов: [38 46 63]
   Их средние баллы: [82.  86.  80.8]
2) Экзамены со средним баллом < 60: 5
   Индексы экзаменов: [0 1 2 3 4]
   Средние баллы экзамена: [49.84 47.64 50.75 52.65 46.17]
3) Массив оценок после изменения оценок < 40 на 40 (пересдача):
[[ 51  92  40  71  60]
 [ 40  82  86  74  74]
 [ 87  99  40  40  40]
 [ 52  40  87  40  40]
 [ 40  63  59  40  40]
 [ 75  57  40  88  48]
 [ 90  58  41  91  59]
 [ 79  40  61  61  46]
 [ 61  50  54  63  40]
 [100  50  40  40  72]]


In [51]:
np.random.seed(42)

X = np.random.randn(1000, 10)      # 1000 примеров, 10 признаков
weights = np.random.randn(10, 1)   # веса для 10 признаков
bias = np.random.randn()

# Посчитать predictions для всех 1000 примеров за одну операцию
Y = X @ weights + bias # predictions
print(f"Предсказание каждого примера: \n{Y[:10]}")
print(f"Предсказание каждого примера в сокращенном виде: \n{Y[:10].flatten()}") #преобразование в одномерный массив

Предсказание каждого примера: 
[[ 2.13131956]
 [-2.25438733]
 [-2.11370319]
 [ 5.60945936]
 [-3.83246301]
 [ 1.72742896]
 [ 0.06848635]
 [-4.75294333]
 [ 0.96913201]
 [ 1.49830847]]
Предсказание каждого примера в сокращенном виде: 
[ 2.13131956 -2.25438733 -2.11370319  5.60945936 -3.83246301  1.72742896
  0.06848635 -4.75294333  0.96913201  1.49830847]


Вывод:
 узнал о практической части работы с numpy, использовал на деле разные функции и стороны библиотеки, опираясь на моделирование реальных ситуаций. Также понял о разнице в скорости работы с numpy и без: огромная разница в скорости и удобстве. Очень удобным оказался broadcasting. Сложность возникла лишь к привыканию синтаксиса и логики инструментов numpy.